export const SUBJECTS = [
  "English Language",
  "Mathematics",
  "Civics",
  "Biology",
  "Chemistry",
  "Physics",
  "Basic Science",
  "Basic Technology",
  "Home Economics",
  "French",
  "Agricultural Science",
  "Computer Studies",
  "IRK/CRK",
  "Physical & Health Education",
  "Cultural and Creative Arts",
];
